development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: aio_development
  pool: 5
  username: aio
  password: aioaiaiaiaiaiaioaio
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: aio_test
  pool: 5
  username: aio
  password: aioaiaiaiaiaiaioaio
  host: localhost

staging:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: aio_staging
  pool: 5
  username: aio
  password: aioaiaiaiaiaiaioaio
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: aio_production
  pool: 5
  username: aio
  password: aioaiaiaiaiaiaioaio
  host: localhost
